### ISSUE TITLE
example-multiclusterhub-cr.yaml in multiclusterhub/ is incomplete

### ISSUE THREAD

**Issue by drkho** [open-cluster-management/deploy#65]
Current example-multiclusterhub-cr.yaml in multiclusterhub is incomplete. After I replace it with the content from README, the deployment of ACM became successful.

```
apiVersion: operators.open-cluster-management.io/v1beta1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  imageRepository: "quay.io/open-cluster-management"
  imageTagSuffix: SNAPSHOT-2020-04-21-17-28-34
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
```

Expected content is (from README):
```
apiVersion: operators.open-cluster-management.io/v1beta1
kind: MultiClusterHub
metadata:
  name: example-multiclusterhub
  namespace: open-cluster-management
spec:
  version: latest
  imageRepository: "quay.io/open-cluster-management"
  imageTagSuffix: "SNAPSHOT-2020-03-17-21-24-18"
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
  foundation:
    apiserver:
      configuration:
        http2-max-streams-per-connection: "1000"
      replicas: 1
      apiserverSecret: "mcm-apiserver-self-signed-secrets"
      klusterletSecret: "mcm-klusterlet-self-signed-secrets"
    controller:
      configuration:
        enable-rbac: "true"
        enable-service-registry: "true"
      replicas: 1
  mongo:
    endpoints: mongo-0.mongo.open-cluster-management
    replicaSet: rs0
  hive:
    additionalCertificateAuthorities:
      - name: letsencrypt-ca
    managedDomains:
      - s1.openshiftapps.com
    globalPullSecret:
      name: private-secret
    failedProvisionConfig:
      skipGatherLogs: true
```

**Comment by nathanweatherly** [comment]
Readme is out of date, sorry about that. @zkayyali812 made changes so this should work with updated version. @zkayyali812 can you take a look?

**Comment by zkayyali812** [comment]
@drkho 
This example in the README - 
```
apiVersion: operators.open-cluster-management.io/v1beta1
kind: MultiClusterHub
metadata:
  name: example-multiclusterhub
  namespace: open-cluster-management
spec:
  version: latest
  imageRepository: "quay.io/open-cluster-management"
  imageTagSuffix: "SNAPSHOT-2020-03-17-21-24-18"
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
  foundation:
    apiserver:
      configuration:
        http2-max-streams-per-connection: "1000"
      replicas: 1
      apiserverSecret: "mcm-apiserver-self-signed-secrets"
      klusterletSecret: "mcm-klusterlet-self-signed-secrets"
    controller:
      configuration:
        enable-rbac: "true"
        enable-service-registry: "true"
      replicas: 1
  mongo:
    endpoints: mongo-0.mongo.open-cluster-management
    replicaSet: rs0
  hive:
    additionalCertificateAuthorities:
      - name: letsencrypt-ca
    managedDomains:
      - s1.openshiftapps.com
    globalPullSecret:
      name: private-secret
    failedProvisionConfig:
      skipGatherLogs: true
```
is using an older snapshot and format, and this example should be updated

Although the above example -
```
apiVersion: operators.open-cluster-management.io/v1beta1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  imageRepository: "quay.io/open-cluster-management"
  imageTagSuffix: SNAPSHOT-2020-04-21-17-28-34
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
```
is valid. I tested this on a fresh cluster using this deploy repo with and it has deployed successfully - 
```
Client Version: openshift-clients-4.3.7-202003130552
Server Version: 4.3.10
Kubernetes Version: v1.16.2
```

Are you still seeing this error, and if so can you update with your version info and any logs?
